#!/bin/bash

. scripts/common

timeout -k "${TIMEOUT[0]}" "${TIMEOUT[1]}" \
  $GHC -o kek Main.hs $2 \
  -ddump-simpl \
  -dsuppress-all \
  -dno-suppress-type-signatures \
  -ddump-to-file

cat Main.dump-simpl 1>&2
